### ISSUE TITLE
portfolio

### ISSUE THREAD

**Issue by ennynz** [webkea/website#5]
need to update portfolio images and add links to them.

**Comment by ennynz** [comment]
explore adding lightbox to portfolio gallery with descriptions...

**Comment by jaeming** [comment]
looking at the original webkea site, it seems we have lost the borders for the portfolio images which I think looked good.  Also, we messed up the hover size at some point which should make them get larger rather than smaller. I've addressed both of these here: https://github.com/webkea/website/commit/494cf8550c0eab70893cd81cffbb9e52fb3857c7

**Comment by jaeming** [comment]
Added portfolio description text for lightbox: https://github.com/webkea/website/commit/e7792c5883bb7c881ab4390f1bb6dd26b599c027

I think the only other thing we need to close this is to style it for mobile sizes. The lightbox is not responsive at all. Also, would be nice to give it overall better styling I think.  The description text should maybe be a part of the image card. think Polaroid maybe.

**Comment by ennynz** [comment]
lets call this done for v1
